version: '3.1'

services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vuegodb
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: vuegodb

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 1200:8080